<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>acc11149-534a-4951-9f9a-b7a2014e9908</elementGuidId>
    <imagePath></imagePath>
    <name>form_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/div[2]/div[1]/div[1]/form[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ng-pristine\ ng-valid"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'ng-valid ng-dirty ng-valid-parse')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>ng-valid ng-dirty ng-valid-parse</value>
        <webElementGuid>1909ec17-5669-4ae7-b07f-cbe62afc98a5</webElementGuid>
    </webElementProperties>
</WebElementEntity>