<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a7a294bc-8a4f-47c8-a79f-701c77058c04</elementGuidId>
    <imagePath></imagePath>
    <name>select_type</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/div[2]/div[1]/div[1]/form[1]/select[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ng-pristine\ ng-valid"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'type') and equals(@class,'input ng-untouched ng-valid ng-not-empty ng-dirty ng-valid-parse')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>input ng-untouched ng-valid ng-not-empty ng-dirty ng-valid-parse</value>
        <webElementGuid>15dc5160-8bbc-4c6c-b31f-f1dae8e2d769</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>type</value>
        <webElementGuid>4f166a25-212d-4351-b264-d073a6a37988</webElementGuid>
    </webElementProperties>
</WebElementEntity>