<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>cdca3eb9-a4df-4aff-9d3f-64e6644df6c2</elementGuidId>
    <imagePath></imagePath>
    <name>select_fromaccountid</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/div[2]/div[1]/div[1]/form[1]/select[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ng-pristine\ ng-valid"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'fromAccountId') and equals(@class,'input ng-untouched ng-valid ng-not-empty ng-dirty ng-valid-parse')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>input ng-untouched ng-valid ng-not-empty ng-dirty ng-valid-parse</value>
        <webElementGuid>f5bd95f9-490d-45e7-acbb-731f4afe1480</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>fromAccountId</value>
        <webElementGuid>d22a2a96-ef25-454f-8623-dc798f53b68f</webElementGuid>
    </webElementProperties>
</WebElementEntity>